services:
  template-db:
    image: postgres
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PW}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_NAME}
